/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpstore;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author User
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Clientes() {
        initComponents();
        this.setTitle("Clientes - MP store");
        
        this.setLocationRelativeTo(null);
        //setIconImage(new ImageIcon(getClass().getResource("imagenes1/LogoFamil.png")).getImage());
    }
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes1/icono.png"));
       return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonClientes = new javax.swing.JButton();
        jButtonFac = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jButtonBuscarCliente = new javax.swing.JButton();
        jButtonClienteModificar = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonClientes.setBackground(new java.awt.Color(204, 0, 51));
        jButtonClientes.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonClientes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/productos bien.png"))); // NOI18N
        jButtonClientes.setText("REGISTRAR");
        jButtonClientes.setBorder(null);
        jButtonClientes.setBorderPainted(false);
        jButtonClientes.setContentAreaFilled(false);
        jButtonClientes.setFocusPainted(false);
        jButtonClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClientes.setOpaque(true);
        jButtonClientes.setRequestFocusEnabled(false);
        jButtonClientes.setRolloverEnabled(false);
        jButtonClientes.setVerifyInputWhenFocusTarget(false);
        jButtonClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 190, 210));

        jButtonFac.setBackground(new java.awt.Color(204, 0, 51));
        jButtonFac.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonFac.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/inventario bien.png"))); // NOI18N
        jButtonFac.setText("SEPARADOS");
        jButtonFac.setBorder(null);
        jButtonFac.setBorderPainted(false);
        jButtonFac.setContentAreaFilled(false);
        jButtonFac.setDefaultCapable(false);
        jButtonFac.setFocusPainted(false);
        jButtonFac.setFocusable(false);
        jButtonFac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFac.setOpaque(true);
        jButtonFac.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 310, 190, 210));

        jButtonAtras.setBackground(new java.awt.Color(204, 0, 51));
        jButtonAtras.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/atrasBlanco.png"))); // NOI18N
        jButtonAtras.setBorder(null);
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setContentAreaFilled(false);
        jButtonAtras.setFocusPainted(false);
        jButtonAtras.setOpaque(true);
        jButtonAtras.setRequestFocusEnabled(false);
        jButtonAtras.setRolloverEnabled(false);
        jButtonAtras.setVerifyInputWhenFocusTarget(false);
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 120, 40));

        jButtonBuscarCliente.setBackground(new java.awt.Color(204, 0, 51));
        jButtonBuscarCliente.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/buscar bien.png"))); // NOI18N
        jButtonBuscarCliente.setText("BUSCAR");
        jButtonBuscarCliente.setBorder(null);
        jButtonBuscarCliente.setBorderPainted(false);
        jButtonBuscarCliente.setContentAreaFilled(false);
        jButtonBuscarCliente.setFocusPainted(false);
        jButtonBuscarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBuscarCliente.setOpaque(true);
        jButtonBuscarCliente.setRequestFocusEnabled(false);
        jButtonBuscarCliente.setRolloverEnabled(false);
        jButtonBuscarCliente.setVerifyInputWhenFocusTarget(false);
        jButtonBuscarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 190, -1));

        jButtonClienteModificar.setBackground(new java.awt.Color(204, 0, 51));
        jButtonClienteModificar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonClienteModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClienteModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/modificar bien.png"))); // NOI18N
        jButtonClienteModificar.setText("MODIFICAR");
        jButtonClienteModificar.setBorder(null);
        jButtonClienteModificar.setBorderPainted(false);
        jButtonClienteModificar.setContentAreaFilled(false);
        jButtonClienteModificar.setFocusPainted(false);
        jButtonClienteModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClienteModificar.setOpaque(true);
        jButtonClienteModificar.setRequestFocusEnabled(false);
        jButtonClienteModificar.setRolloverEnabled(false);
        jButtonClienteModificar.setVerifyInputWhenFocusTarget(false);
        jButtonClienteModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClienteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClienteModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 40, 180, 220));

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/cajon_1.jpeg"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -10, 1310, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        RegistrarCliente R = new RegistrarCliente();
        R.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        Inicio1 I = new Inicio1();
        I.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        BuscarCliente B = new BuscarCliente();
        B.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonClienteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteModificarActionPerformed
        ModificarCliente M = new ModificarCliente();
        M.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonClienteModificarActionPerformed

    private void jButtonFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacActionPerformed
        Separado M = new Separado();
        M.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButtonFacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonClienteModificar;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonFac;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    // End of variables declaration//GEN-END:variables
}
