/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpstore;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
/**
 *
 * @author User
 */
public class Inicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio1() {
        initComponents();
        this.setTitle("Facturar MP - store");
        this.setLocationRelativeTo(null);
        transpareciaBoton();
        //setIconImage(new ImageIcon(getClass().getResource("imagenes1/LogoFamil.png")).getImage());
    }
    public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes1/icono.png"));
       return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFac3 = new javax.swing.JButton();
        jButtonInicio = new javax.swing.JButton();
        jButtonFac = new javax.swing.JButton();
        jButtonFac2 = new javax.swing.JButton();
        jButtonFac1 = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonFac3.setBackground(new java.awt.Color(204, 0, 51));
        jButtonFac3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonFac3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFac3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/clientes bien.png"))); // NOI18N
        jButtonFac3.setText("CLIENTES");
        jButtonFac3.setBorder(null);
        jButtonFac3.setBorderPainted(false);
        jButtonFac3.setContentAreaFilled(false);
        jButtonFac3.setDefaultCapable(false);
        jButtonFac3.setFocusPainted(false);
        jButtonFac3.setFocusable(false);
        jButtonFac3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFac3.setOpaque(true);
        jButtonFac3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFac3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFac3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFac3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 70, 180, 200));

        jButtonInicio.setBackground(new java.awt.Color(204, 0, 51));
        jButtonInicio.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonInicio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/inicio.png"))); // NOI18N
        jButtonInicio.setBorderPainted(false);
        jButtonInicio.setContentAreaFilled(false);
        jButtonInicio.setOpaque(true);
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, -1));

        jButtonFac.setBackground(new java.awt.Color(204, 0, 51));
        jButtonFac.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonFac.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/inventario bien.png"))); // NOI18N
        jButtonFac.setText("INVENTARIO");
        jButtonFac.setBorder(null);
        jButtonFac.setBorderPainted(false);
        jButtonFac.setContentAreaFilled(false);
        jButtonFac.setDefaultCapable(false);
        jButtonFac.setFocusPainted(false);
        jButtonFac.setFocusable(false);
        jButtonFac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFac.setOpaque(true);
        jButtonFac.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, 180, 200));

        jButtonFac2.setBackground(new java.awt.Color(204, 0, 51));
        jButtonFac2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonFac2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFac2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/productos bien.png"))); // NOI18N
        jButtonFac2.setText("PRODUCTOS");
        jButtonFac2.setBorder(null);
        jButtonFac2.setBorderPainted(false);
        jButtonFac2.setContentAreaFilled(false);
        jButtonFac2.setDefaultCapable(false);
        jButtonFac2.setFocusPainted(false);
        jButtonFac2.setFocusable(false);
        jButtonFac2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFac2.setOpaque(true);
        jButtonFac2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFac2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 180, 210));

        jButtonFac1.setBackground(new java.awt.Color(204, 0, 51));
        jButtonFac1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonFac1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFac1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/facturar bien.png"))); // NOI18N
        jButtonFac1.setText("FACTURAR");
        jButtonFac1.setBorder(null);
        jButtonFac1.setBorderPainted(false);
        jButtonFac1.setContentAreaFilled(false);
        jButtonFac1.setDefaultCapable(false);
        jButtonFac1.setFocusPainted(false);
        jButtonFac1.setFocusable(false);
        jButtonFac1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFac1.setOpaque(true);
        jButtonFac1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFac1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 180, 200));

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/Mp logo.jpeg"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1310, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void transpareciaBoton(){
        
    }
    private void jButtonFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacActionPerformed
        Inventario M = new Inventario();
        M.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButtonFacActionPerformed

    private void jButtonFac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFac1ActionPerformed
        FacturaPrint F = new FacturaPrint(this, true);
        F.setVisible(true);
    }//GEN-LAST:event_jButtonFac1ActionPerformed

    private void jButtonFac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFac2ActionPerformed
        Productos M = new Productos();
        M.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFac2ActionPerformed

    private void jButtonFac3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFac3ActionPerformed
        Clientes R = new Clientes();
        R.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFac3ActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        Ventana_principal.Inicio I = new Ventana_principal.Inicio();
        I.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFac;
    private javax.swing.JButton jButtonFac1;
    private javax.swing.JButton jButtonFac2;
    private javax.swing.JButton jButtonFac3;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    // End of variables declaration//GEN-END:variables
}
